spring:
  profiles:
    active: local
  jpa:
    properties:
      hibernate:
        create_empty_composites:
          enabled: true

springdoc:
  packagesToScan: com.portfolio.rebalancer
  swagger-ui:
    path: /api-docs
    groups:
      enabled: false

logging:
  level:
    org.hibernate:
      SQL: debug
      type: trace
