spring:
  profiles:
    active: local

springdoc:
  packagesToScan: com.portfolio.rebalancer
  swagger-ui:
    path: /api-docs
    groups:
      enabled: false

logging:
  level:
    org.hibernate:
      SQL: debug
      type: trace
